version: "3.8"

services:
  js-project:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: js-project-container
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
